Repository International-Data-Spaces-Association/DSC-Camel-Instance, pull requests merged in 2021-06, with the labels that each got.

#36 Remove RollingFileAppender
  CHANGELOG.md
  src/main/resources/log4j2.xml
Labels: maintenance

#40 fix: remove custom connection manager for HTTP component
  CHANGELOG.md
  pom.xml
  src/main/java/de/fraunhofer/isst/dataspaceconnector/camel/config/context/CamelHttpConfig.java
Labels: bug

#41 chore: add vulnerability scanning
  .github/workflows/build-image.yaml
Labels: maintenance

#43 feat: log route errors to config manager
  CHANGELOG.md
  pom.xml
  src/main/java/de/fraunhofer/isst/dataspaceconnector/camel/config/context/ErrorHandlerConfig.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/camel/errorhandling/DeadLetterChannel.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/camel/errorhandling/DeadLetterChannelProcessor.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/camel/errorhandling/RouteError.java
  src/main/resources/application.properties
Labels: enhancement

#45 chore: add dockerfile linting
  .github/workflows/main.yml
  .hadolint.yaml
Labels: maintenance

#46 chore: test against java 16
  .github/workflows/main.yml
  .hadolint.yaml
Labels: maintenance

#47 chore: timestamp for error logs
  CHANGELOG.md
  src/main/java/de/fraunhofer/isst/dataspaceconnector/camel/errorhandling/DeadLetterChannelProcessor.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/camel/errorhandling/RouteError.java
Labels: maintenance
